MvcCachingContent/Controllers/CodeCachingController.cs
using System;
using System.Diagnostics;
using System.Web.Mvc;
using MvcCachingContent.Infrastructure;

namespace MvcCachingContent.Controllers
{
    public class CodeCachingController : Controller
    {
        CachingConfigurationLogic cacheSettingsHelper = new CachingConfigurationLogic();

        public ActionResult Index()
        {
            cacheSettingsHelper.DetectConfiguration(Request.RawUrl, Response.Cache);

            int counterValue = AppStateHelper.IncrementAndGet(AppStateKeys.IndexCounter);
            Debug.WriteLine($"IndexCounter: {counterValue}");
            return View("~/Views/CachingChildAction/Index.cshtml", (object)counterValue);
        }

        [ChildActionOnly]
        public PartialViewResult GetTime()
        {
            return PartialView("~/Views/CachingChildAction/GetTime.cshtml", (object)DateTime.Now.ToLongTimeString());
        }
    }
}

MvcCachingContent/Controllers/DonutController.cs
using System;
using System.Diagnostics;
using System.Web.Mvc;
using DevTrends.MvcDonutCaching;
using MvcCachingContent.Infrastructure;

namespace MvcCachingContent.Controllers
{
    /// <summary>
    /// https://github.com/moonpyk/mvcdonutcaching
    /// The package adds several overloads to the built-in Html.Action HTML helper.
    /// The extra parameter in each overload is named excludeFromParentCache.
    /// @Html.Action("Login", "Account", true)
    /// </summary>
    public class DonutController : Controller
    {
        [DonutOutputCache(Duration = 20)]
        public ActionResult Index()
        {
            int counterValue = AppStateHelper.IncrementAndGet(AppStateKeys.IndexCounter);
            Debug.WriteLine($"IndexCounter: {counterValue}");
            return View((object)counterValue);
        }

        [ChildActionOnly]
        public PartialViewResult GetTime()
        {
            return PartialView("~/Views/CachingChildAction/GetTime.cshtml", (object)DateTime.Now.ToLongTimeString());
        }
    }
}

MvcCachingContent/Controllers/DonutHoleController.cs
using System;
using System.Diagnostics;
using System.Web.Mvc;
using MvcCachingContent.Infrastructure;

namespace MvcCachingContent.Controllers
{
    public class DonutHoleController : Controller
    {
        public ActionResult Index()
        {
            int counterValue = AppStateHelper.IncrementAndGet(AppStateKeys.IndexCounter);
            Debug.WriteLine($"IndexCounter: {counterValue}");
            return View("~/Views/CachingChildAction/Index.cshtml", (object)counterValue);
        }

        [ChildActionOnly]
        [OutputCache(Duration = 20)]
        public PartialViewResult GetTime()
        {
            return PartialView("~/Views/CachingChildAction/GetTime.cshtml", (object)DateTime.Now.ToShortTimeString());
        }
    }
}

MvcCachingContent/Views/Shared/Many.cshtml
@model Dictionary<string, string>

@{
    Layout = "_Layout.cshtml";
}

<div class="panel panel-primary">
    <div class="panel-heading">Configuration Data</div>
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Property</th>
            <th>Value</th>
        </tr>
        </thead>
        <tbody>
            @foreach (string key in Model.Keys)
            {
                <tr>
                    <td>@key</td>
                    <td>@Model[key]</td>
                </tr>
            }
        </tbody>
    </table>
</div>

MvcCachingContent/Views/Shared/One.cshtml
@model System.Int32?

@{
    Layout = "_Layout.cshtml";
}

<div class="alert alert-success">Value: @Model</div>

@Html.ActionLink("Update", "Index", null, new { @class = "btn btn-primary" })

MvcCachingContent/Views/Shared/_Layout.cshtml
@{
    var appName = "MvcCachingContent";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@appName</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <!--<script src="~/Scripts/modernizr-2.6.2.js"></script>-->
</head>
<body class="container">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink($"Sukhoi1: {appName}", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home-Increment", "Index", "Home")</li>
                    <li>@Html.ActionLink("Location", "Index", "Location")</li>
                    <li>@Html.ActionLink("VaryByHeader", "Index", "VaryByHeader")</li>
                    <li>@Html.ActionLink("VaryByParam", "Index", "VaryByParam", new {name = "some", city = "London"}, null)</li>
                    <li>@Html.ActionLink("VaryByCustom", "Index", "VaryByCustom")</li>
                    <li>@Html.ActionLink("CacheProfiles", "Index", "CacheProfiles")</li>
                    <li>@Html.ActionLink("CachingChildAction", "Index", "CachingChildAction")</li>
                    <li>@Html.ActionLink("DonutHoleCaching", "Index", "DonutHole")</li>
                    <li>@Html.ActionLink("DonutCaching", "Index", "Donut")</li>
                    <li>@Html.ActionLink("CacheProfilesDisable", "Index", "CacheProfilesDisable")</li>
                    <li>@Html.ActionLink("CachingConfigFromCode", "Index", "CodeCaching")</li>
                    <li>@Html.ActionLink("ValidatingCachedContent", "Index", "ValidatingCachedContent")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>@DateTime.Now.Year &copy; @appName</p>
        </footer>
    </div>

    <!--<script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>-->
</body>
</html>